### ISSUE TITLE
Email and "+" character

### ISSUE THREAD

**Issue by arkhi** [DrKLO/Telegram#997]
[RFC5322](https://tools.ietf.org/html/rfc5322#section-3.4.1) allows the usage of `+` in e-mails.

All mail that is sent to user+foo@example.com, user+bar@example.com ends up in user@example.com mailbox.

This allows to define filters based on the information you decide to provide to different services, while still keeping the same recipient email.

Telegram does not seem to follow this RFC, as an email with "+" in it will be recognized as faulty during the two steps verification process.

**Comment by Alex131089** [comment]
Agreed, had the same problem.

**Comment by DrKLO** [comment]
Is was server side. Is it fixed now?

**Comment by arkhi** [comment]
I just tried with the Android version and still receive an "Invalid email" error message.

**Comment by DrKLO** [comment]
Can you check it now?

**Comment by arkhi** [comment]
Worked like a charm, thanks!
